/**
 */
package de.oaam.model.oaam.safety.failurePropagations.failurePropagationMatrices.provider;

import de.oaam.model.oaam.safety.failurePropagations.failurePropagationMatrices.util.FailurePropagationMatricesAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class FailurePropagationMatricesItemProviderAdapterFactory extends FailurePropagationMatricesAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public FailurePropagationMatricesItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.oaam.model.oaam.safety.failurePropagations.failurePropagationMatrices.FailureModeMatrix} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FailureModeMatrixItemProvider failureModeMatrixItemProvider;

	/**
	 * This creates an adapter for a {@link de.oaam.model.oaam.safety.failurePropagations.failurePropagationMatrices.FailureModeMatrix}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFailureModeMatrixAdapter() {
		if (failureModeMatrixItemProvider == null) {
			failureModeMatrixItemProvider = new FailureModeMatrixItemProvider(this);
		}

		return failureModeMatrixItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.oaam.model.oaam.safety.failurePropagations.failurePropagationMatrices.IntegrityStateMatrix} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IntegrityStateMatrixItemProvider integrityStateMatrixItemProvider;

	/**
	 * This creates an adapter for a {@link de.oaam.model.oaam.safety.failurePropagations.failurePropagationMatrices.IntegrityStateMatrix}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIntegrityStateMatrixAdapter() {
		if (integrityStateMatrixItemProvider == null) {
			integrityStateMatrixItemProvider = new IntegrityStateMatrixItemProvider(this);
		}

		return integrityStateMatrixItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.oaam.model.oaam.safety.failurePropagations.failurePropagationMatrices.BooleanMatrix} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BooleanMatrixItemProvider booleanMatrixItemProvider;

	/**
	 * This creates an adapter for a {@link de.oaam.model.oaam.safety.failurePropagations.failurePropagationMatrices.BooleanMatrix}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBooleanMatrixAdapter() {
		if (booleanMatrixItemProvider == null) {
			booleanMatrixItemProvider = new BooleanMatrixItemProvider(this);
		}

		return booleanMatrixItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.oaam.model.oaam.safety.failurePropagations.failurePropagationMatrices.FailureModeInport} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FailureModeInportItemProvider failureModeInportItemProvider;

	/**
	 * This creates an adapter for a {@link de.oaam.model.oaam.safety.failurePropagations.failurePropagationMatrices.FailureModeInport}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFailureModeInportAdapter() {
		if (failureModeInportItemProvider == null) {
			failureModeInportItemProvider = new FailureModeInportItemProvider(this);
		}

		return failureModeInportItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.oaam.model.oaam.safety.failurePropagations.failurePropagationMatrices.FailureModeOutport} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FailureModeOutportItemProvider failureModeOutportItemProvider;

	/**
	 * This creates an adapter for a {@link de.oaam.model.oaam.safety.failurePropagations.failurePropagationMatrices.FailureModeOutport}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFailureModeOutportAdapter() {
		if (failureModeOutportItemProvider == null) {
			failureModeOutportItemProvider = new FailureModeOutportItemProvider(this);
		}

		return failureModeOutportItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.oaam.model.oaam.safety.failurePropagations.failurePropagationMatrices.FailureModeMatrixRow} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FailureModeMatrixRowItemProvider failureModeMatrixRowItemProvider;

	/**
	 * This creates an adapter for a {@link de.oaam.model.oaam.safety.failurePropagations.failurePropagationMatrices.FailureModeMatrixRow}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFailureModeMatrixRowAdapter() {
		if (failureModeMatrixRowItemProvider == null) {
			failureModeMatrixRowItemProvider = new FailureModeMatrixRowItemProvider(this);
		}

		return failureModeMatrixRowItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.oaam.model.oaam.safety.failurePropagations.failurePropagationMatrices.FailureModeInportEntry} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FailureModeInportEntryItemProvider failureModeInportEntryItemProvider;

	/**
	 * This creates an adapter for a {@link de.oaam.model.oaam.safety.failurePropagations.failurePropagationMatrices.FailureModeInportEntry}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFailureModeInportEntryAdapter() {
		if (failureModeInportEntryItemProvider == null) {
			failureModeInportEntryItemProvider = new FailureModeInportEntryItemProvider(this);
		}

		return failureModeInportEntryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.oaam.model.oaam.safety.failurePropagations.failurePropagationMatrices.FailureModeOutportEntry} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FailureModeOutportEntryItemProvider failureModeOutportEntryItemProvider;

	/**
	 * This creates an adapter for a {@link de.oaam.model.oaam.safety.failurePropagations.failurePropagationMatrices.FailureModeOutportEntry}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFailureModeOutportEntryAdapter() {
		if (failureModeOutportEntryItemProvider == null) {
			failureModeOutportEntryItemProvider = new FailureModeOutportEntryItemProvider(this);
		}

		return failureModeOutportEntryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.oaam.model.oaam.safety.failurePropagations.failurePropagationMatrices.IntegrityStateOutport} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IntegrityStateOutportItemProvider integrityStateOutportItemProvider;

	/**
	 * This creates an adapter for a {@link de.oaam.model.oaam.safety.failurePropagations.failurePropagationMatrices.IntegrityStateOutport}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIntegrityStateOutportAdapter() {
		if (integrityStateOutportItemProvider == null) {
			integrityStateOutportItemProvider = new IntegrityStateOutportItemProvider(this);
		}

		return integrityStateOutportItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.oaam.model.oaam.safety.failurePropagations.failurePropagationMatrices.IntegrityStateInport} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IntegrityStateInportItemProvider integrityStateInportItemProvider;

	/**
	 * This creates an adapter for a {@link de.oaam.model.oaam.safety.failurePropagations.failurePropagationMatrices.IntegrityStateInport}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIntegrityStateInportAdapter() {
		if (integrityStateInportItemProvider == null) {
			integrityStateInportItemProvider = new IntegrityStateInportItemProvider(this);
		}

		return integrityStateInportItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.oaam.model.oaam.safety.failurePropagations.failurePropagationMatrices.IntegrityStateMatrixRow} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IntegrityStateMatrixRowItemProvider integrityStateMatrixRowItemProvider;

	/**
	 * This creates an adapter for a {@link de.oaam.model.oaam.safety.failurePropagations.failurePropagationMatrices.IntegrityStateMatrixRow}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIntegrityStateMatrixRowAdapter() {
		if (integrityStateMatrixRowItemProvider == null) {
			integrityStateMatrixRowItemProvider = new IntegrityStateMatrixRowItemProvider(this);
		}

		return integrityStateMatrixRowItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.oaam.model.oaam.safety.failurePropagations.failurePropagationMatrices.IntegrityStateInportEntry} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IntegrityStateInportEntryItemProvider integrityStateInportEntryItemProvider;

	/**
	 * This creates an adapter for a {@link de.oaam.model.oaam.safety.failurePropagations.failurePropagationMatrices.IntegrityStateInportEntry}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIntegrityStateInportEntryAdapter() {
		if (integrityStateInportEntryItemProvider == null) {
			integrityStateInportEntryItemProvider = new IntegrityStateInportEntryItemProvider(this);
		}

		return integrityStateInportEntryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.oaam.model.oaam.safety.failurePropagations.failurePropagationMatrices.IntegrityStateOutportEntry} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IntegrityStateOutportEntryItemProvider integrityStateOutportEntryItemProvider;

	/**
	 * This creates an adapter for a {@link de.oaam.model.oaam.safety.failurePropagations.failurePropagationMatrices.IntegrityStateOutportEntry}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIntegrityStateOutportEntryAdapter() {
		if (integrityStateOutportEntryItemProvider == null) {
			integrityStateOutportEntryItemProvider = new IntegrityStateOutportEntryItemProvider(this);
		}

		return integrityStateOutportEntryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.oaam.model.oaam.safety.failurePropagations.failurePropagationMatrices.BooleanInport} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BooleanInportItemProvider booleanInportItemProvider;

	/**
	 * This creates an adapter for a {@link de.oaam.model.oaam.safety.failurePropagations.failurePropagationMatrices.BooleanInport}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBooleanInportAdapter() {
		if (booleanInportItemProvider == null) {
			booleanInportItemProvider = new BooleanInportItemProvider(this);
		}

		return booleanInportItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.oaam.model.oaam.safety.failurePropagations.failurePropagationMatrices.BooleanOutport} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BooleanOutportItemProvider booleanOutportItemProvider;

	/**
	 * This creates an adapter for a {@link de.oaam.model.oaam.safety.failurePropagations.failurePropagationMatrices.BooleanOutport}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBooleanOutportAdapter() {
		if (booleanOutportItemProvider == null) {
			booleanOutportItemProvider = new BooleanOutportItemProvider(this);
		}

		return booleanOutportItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.oaam.model.oaam.safety.failurePropagations.failurePropagationMatrices.BooleanMatrixRow} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BooleanMatrixRowItemProvider booleanMatrixRowItemProvider;

	/**
	 * This creates an adapter for a {@link de.oaam.model.oaam.safety.failurePropagations.failurePropagationMatrices.BooleanMatrixRow}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBooleanMatrixRowAdapter() {
		if (booleanMatrixRowItemProvider == null) {
			booleanMatrixRowItemProvider = new BooleanMatrixRowItemProvider(this);
		}

		return booleanMatrixRowItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.oaam.model.oaam.safety.failurePropagations.failurePropagationMatrices.BooleanInportEntry} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BooleanInportEntryItemProvider booleanInportEntryItemProvider;

	/**
	 * This creates an adapter for a {@link de.oaam.model.oaam.safety.failurePropagations.failurePropagationMatrices.BooleanInportEntry}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBooleanInportEntryAdapter() {
		if (booleanInportEntryItemProvider == null) {
			booleanInportEntryItemProvider = new BooleanInportEntryItemProvider(this);
		}

		return booleanInportEntryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link de.oaam.model.oaam.safety.failurePropagations.failurePropagationMatrices.BooleanOutportEntry} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BooleanOutportEntryItemProvider booleanOutportEntryItemProvider;

	/**
	 * This creates an adapter for a {@link de.oaam.model.oaam.safety.failurePropagations.failurePropagationMatrices.BooleanOutportEntry}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBooleanOutportEntryAdapter() {
		if (booleanOutportEntryItemProvider == null) {
			booleanOutportEntryItemProvider = new BooleanOutportEntryItemProvider(this);
		}

		return booleanOutportEntryItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (failureModeMatrixItemProvider != null) failureModeMatrixItemProvider.dispose();
		if (integrityStateMatrixItemProvider != null) integrityStateMatrixItemProvider.dispose();
		if (booleanMatrixItemProvider != null) booleanMatrixItemProvider.dispose();
		if (failureModeInportItemProvider != null) failureModeInportItemProvider.dispose();
		if (failureModeOutportItemProvider != null) failureModeOutportItemProvider.dispose();
		if (failureModeMatrixRowItemProvider != null) failureModeMatrixRowItemProvider.dispose();
		if (failureModeInportEntryItemProvider != null) failureModeInportEntryItemProvider.dispose();
		if (failureModeOutportEntryItemProvider != null) failureModeOutportEntryItemProvider.dispose();
		if (integrityStateOutportItemProvider != null) integrityStateOutportItemProvider.dispose();
		if (integrityStateInportItemProvider != null) integrityStateInportItemProvider.dispose();
		if (integrityStateMatrixRowItemProvider != null) integrityStateMatrixRowItemProvider.dispose();
		if (integrityStateInportEntryItemProvider != null) integrityStateInportEntryItemProvider.dispose();
		if (integrityStateOutportEntryItemProvider != null) integrityStateOutportEntryItemProvider.dispose();
		if (booleanInportItemProvider != null) booleanInportItemProvider.dispose();
		if (booleanOutportItemProvider != null) booleanOutportItemProvider.dispose();
		if (booleanMatrixRowItemProvider != null) booleanMatrixRowItemProvider.dispose();
		if (booleanInportEntryItemProvider != null) booleanInportEntryItemProvider.dispose();
		if (booleanOutportEntryItemProvider != null) booleanOutportEntryItemProvider.dispose();
	}

}
